version: '2'
volumes:
  mysqldata:
      driver: local

networks:
  backend:
      driver: bridge

services:
  web:
    build: 
      context: .
    image: ojs
    networks:
      - backend
    environment:
      OJS_DB_HOST: db
      OJS_DB_USER: ojs
      OJS_DB_PASSWORD: ojs@#2017
      OJS_DB_NAME: ojs
    ports:
      - 80:80
    volumes:
      - ./www/files:/var/www/files:rw
  db:
    image: mariadb:10.1
    restart: always
    volumes:
      - ./mysql/conf.d:/etc/mysql/conf.d
      - "mysqldata:/var/lib/mysql"
    expose:
      - "3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ojs
      MYSQL_USER: ojs
      MYSQL_PASSWORD: ojs@#2017
    networks:
      - backend  
  pwa:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports: 
      - 3001:80
    environment:
      PMA_HOST: db
    networks:
      - backend  